# ********RoostGPT********

# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=2cd54a0a81
# ROOST_METHOD_SIG_HASH=809947a8ba
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Petstore E2E Flow\r\n' +
#     '    As a user of the Petstore API\r\n' +
#     '    I want to manage pets, orders, and user accounts\r\n' +
#     '    So that I can run a successful pet store business',
#   background: 'Background:\r\n' +
#     '        Given the Petstore API is available at "https://petstore.swagger.io/v2"\r\n' +
#     '        And I have valid API credentials\r\n' +
#     '        And I am authenticated with OAuth2 token with "write:pets" and "read:pets" scopes',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Bulk operations',
#     steps: 'Given I have multiple users to create\r\n' +
#       'When I create users with array input\r\n' +
#       '            | username  | email          | firstName | lastName |\r\n' +
#       '            | bulkuser1 | bulk1@test.com | Bulk      | User1    |\r\n' +
#       '            | bulkuser2 | bulk2@test.com | Bulk      | User2    |\r\n' +
#       'Then all users should be created successfully\r\n' +
#       'Given I have multiple pets to add\r\n' +
#       'When I add the following pets:\r\n' +
#       '            | name    | category | status    |\r\n' +
#       '            | Max     | Dog      | available |\r\n' +
#       '            | Charlie | Dog      | available |\r\n' +
#       'Then all pets should be added successfully',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Petstore E2E Flow

  Background:
    * def SWAGGER_184F1D2B61_URL = karate.properties['SWAGGER_184F1D2B61_URL'] || karate.get('SWAGGER_184F1D2B61_URL', 'http://localhost:4010')
    * def SWAGGER_184F1D2B61_AUTH_TOKEN = karate.properties['SWAGGER_184F1D2B61_AUTH_TOKEN'] || karate.get('SWAGGER_184F1D2B61_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario Outline: Bulk operations
    * url '<SWAGGER_184F1D2B61_URL>'
    Given path '/v2/user/createWithList'
    And request [{ "username": "bulk user1", "email": "bulk1@test.com", "firstName": "Bulk", "lastName": "User1"},
    { "username": "bulk user2", "email": "bulk2@test.com", "firstName": "Bulk", "lastName": "User2" }]
    When method post
    Then status 200
    And match $ == "#[2]"

    * url '<SWAGGER_184F1D2B61_URL>'
    * configure headers = { Authorization: '<SWAGGER_184F1D2B61_AUTH_TOKEN>' }
    Given path '/v2/pet'
    And request [{ "name": "Max", "category": "Dog", "photoUrls": [], "tags": [], "status": "available"},
    { "name": "Charlie", "category": "Dog", "photoUrls": [], "tags": [], "status": "available"}]
    When method post
    Then status 200
    And match $ == "#[2]"

  Examples: 
    | SWAGGER_184F1D2B61_URL   | SWAGGER_184F1D2B61_AUTH_TOKEN |
    | http://localhost:4010   | Bearer_Dummy_Token           |
