# ********RoostGPT********

# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=436997a5cf
# ROOST_METHOD_SIG_HASH=579264a708
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Petstore E2E Flow\r\n' +
#     '    As a user of the Petstore API\r\n' +
#     '    I want to manage pets, orders, and user accounts\r\n' +
#     '    So that I can run a successful pet store business',
#   background: 'Background:\r\n' +
#     '        Given the Petstore API is available at "https://petstore.swagger.io/v2"\r\n' +
#     '        And I have valid API credentials\r\n' +
#     '        And I am authenticated with OAuth2 token with "write:pets" and "read:pets" scopes',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Bulk operations',
#     steps: 'Given I have multiple users to create\r\n' +
#       'When I create users with array input\r\n' +
#       '            | username  | email          | firstName | lastName |\r\n' +
#       '            | bulkuser1 | bulk1@test.com | Bulk      | User1    |\r\n' +
#       '            | bulkuser2 | bulk2@test.com | Bulk      | User2    |\r\n' +
#       'Then all users should be created successfully\r\n' +
#       'Given I have multiple pets to add\r\n' +
#       'When I add the following pets:\r\n' +
#       '            | name    | category | status    |\r\n' +
#       '            | Max     | Dog      | available |\r\n' +
#       '            | Charlie | Dog      | available |\r\n' +
#       'Then all pets should be added successfully',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Petstore E2E Flow
  As a user of the Petstore API
  I want to manage pets, orders, and user accounts
  So that I can run a successful pet store business

  Background:
    * def SWAGGER_184F1D2B61_URL = karate.properties['SWAGGER_184F1D2B61_URL'] || karate.get('SWAGGER_184F1D2B61_URL', 'http://localhost:4010')
    * def SWAGGER_184F1D2B61_AUTH_TOKEN = karate.properties['SWAGGER_184F1D2B61_AUTH_TOKEN'] || karate.get('SWAGGER_184F1D2B61_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario: Validate user created via bulk operations
    Given path 'user/createWithArray'
    And configure headers = { Authorization: '#(SWAGGER_184F1D2B61_AUTH_TOKEN)' }
    And url SWAGGER_184F1D2B61_URL
    When def userObject =
      """
      [
       {
        username: 'bulkuser1', 
        email: 'bulk1@test.com', 
        firstName: 'Bulk', 
        lastName: 'User1'
       }, 
       {
        username: 'bulkuser2', 
        email: 'bulk2@test.com', 
        firstName: 'Bulk', 
        lastName: 'User2'
       }
      ]
      """
    And request userObject
    And method post
    Then status 200

  Scenario: Validate pet 'Max' created
    Given path 'pet'
    And url SWAGGER_184F1D2B61_URL
    And configure headers = { Authorization: '#(SWAGGER_184F1D2B61_AUTH_TOKEN)' }
    When def petObject1 =
      """
      {
       name: 'Max', 
       category: 'Dog', 
       status: 'available'
      }
      """
    And request petObject1
    And method post
    Then status 200

  Scenario: Validate pet 'Charlie' created
    Given path 'pet'
    And url SWAGGER_184F1D2B61_URL
    And configure headers = { Authorization: '#(SWAGGER_184F1D2B61_AUTH_TOKEN)' }
    When def petObject2 =
      """
      {
       name: 'Charlie', 
       category: 'Dog', 
       status: 'available'
      } 
      """
    And request petObject2
    And method post
    Then status 200
