# ********RoostGPT********

# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=d5d39c5661
# ROOST_METHOD_SIG_HASH=58ee5577d0
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testDELETESession',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "Success"\n' +
#       'And the details are:\n' +
#       '    "Deleting session [R64EKX5RG32U]"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test

  Background:
    * def SWAGGER_184F1D2B61_URL = karate.properties['SWAGGER_184F1D2B61_URL'] || karate.get('SWAGGER_184F1D2B61_URL', 'http://localhost:4010')
    * def SWAGGER_184F1D2B61_AUTH_TOKEN = karate.properties['SWAGGER_184F1D2B61_AUTH_TOKEN'] || karate.get('SWAGGER_184F1D2B61_AUTH_TOKEN', 'Bearer_Dummy_Token')
    * url SWAGGER_184F1D2B61_URL
    * configure headers = { Authorization: '#(SWAGGER_184F1D2B61_AUTH_TOKEN)' }

  Scenario Outline: testDELETESession
    Given path 'v2/pet', <petId>
    When method DELETE
    Then status 200
    And match $ == """{ description: '#string', headers: '#object' }"""
    And match each $..scopes contains { scope: '#string', description: '#string' }
    And match each $..security contains { type: 'oauth2', scopes: '#array' }
    And match each $..responses contains { 400: { description: '#string', headers: '#string' }, 404: {description: '#string', headers: '#string' }}

    Examples:
      | petId |
      |   123 |
      |   456 |
      |   789 |
