# ********RoostGPT********

# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=de3cc6074a
# ROOST_METHOD_SIG_HASH=01185979a5
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testGETSessionWithMultipleSearchFilters',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "404 Not Found"\n' +
#       'And the details are:\n' +
#       '    "No sessions found matching criteria"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test

  Background:
    * def SWAGGER_184F1D2B61_URL = karate.properties['SWAGGER_184F1D2B61_URL'] || karate.get('SWAGGER_184F1D2B61_URL', 'http://localhost:4010')
    * def SWAGGER_184F1D2B61_AUTH_TOKEN = karate.properties['SWAGGER_184F1D2B61_AUTH_TOKEN'] || karate.get('SWAGGER_184F1D2B61_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario: testGETSessionWithMultipleSearchFilters
    * url SWAGGER_184F1D2B61_URL
    Given path '/pet/findByTags', {tag: 'testTag'}
    And configure headers = { Authorization: '#(SWAGGER_184F1D2B61_AUTH_TOKEN)' }
    And request read('request.json')
    When method get
    Then status 404
    Then match response == {message: 'No pet found with given tag'}
