# ********RoostGPT********

# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=6c62650aaf
# ROOST_METHOD_SIG_HASH=a9ed531d22
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testAddLocation',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "Success"\n' +
#       'And the details are:\n' +
#       '    "Posting new location [UCLocation-HBER8FXU0J]"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test

  Background:
    * match SWAGGER_184F1D2B61_URL = karate.properties['SWAGGER_184F1D2B61_URL'] || karate.get('SWAGGER_184F1D2B61_URL', 'http://localhost:4010')
    * match SWAGGER_184F1D2B61_AUTH_TOKEN = karate.properties['SWAGGER_184F1D2B61_AUTH_TOKEN'] || karate.get('SWAGGER_184F1D2B61_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario Outline: testAddLocation
    * log 'When the scenario executes'
    * url SWAGGER_184F1D2B61_URL
    * configure headers = { Authorization: '#(SWAGGER_184F1D2B61_AUTH_TOKEN)' }
    Given path '/v2/pet'
    And request """
      { 
        id: 1, 
        name: 'UCLocation-HBER8FXU0J', 
        photoUrls: [''], 
        tags: [{id: 1, name: 'tag1'}], 
        status: 'available'
      }
     """
    When method post
    Then status 200
    * log 'Then the outcome should be Success'
    * log 'Posting new location [UCLocation-HBER8FXU0J]'
    * match response.status == 'Success'
    * match response.details == 'Posting new location [UCLocation-HBER8FXU0J]'

  Scenario Outline: testInvalidAddLocation
    * log 'When the scenario executes'
    * url SWAGGER_184F1D2B61_URL
    * configure headers = { Authorization: '#(SWAGGER_184F1D2B61_AUTH_TOKEN)' }
    Given path '/v2/pet'
    And request """
      { 
        id: 1, 
        name: 'InvalidLocation', 
        photoUrls: [''], 
        tags: [{id: 1, name: 'tag1'}], 
        status: 'invalid'
      }
     """
    When method post
    Then status 400
    * log 'Then the outcome should be Invalid input'
    * match response.status == 'Invalid input'
    * match response.details == 'Invalid ID supplied'
