# ********RoostGPT********

# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=6b08ec1f5e
# ROOST_METHOD_SIG_HASH=4939983de6
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testGETSessionInstanceView',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "Success"\n' +
#       'And the details are:\n' +
#       '    "Retrieving session instance view for event [testsimplesession]"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test

  Background:
    * def SWAGGER_184F1D2B61_URL = karate.properties['SWAGGER_184F1D2B61_URL'] || karate.get('SWAGGER_184F1D2B61_URL', 'http://localhost:4010')
    * def SWAGGER_184F1D2B61_AUTH_TOKEN = karate.properties['SWAGGER_184F1D2B61_AUTH_TOKEN'] || karate.get('SWAGGER_184F1D2B61_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario: testGETSessionInstanceView
    * url SWAGGER_184F1D2B61_URL
    And path 'v2/pet/1'
    And configure headers = { Authorization: #(SWAGGER_184F1D2B61_AUTH_TOKEN) }
    When method get
    Then match status == 200
    And match response.path == '1'
