# ********RoostGPT********

# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=102a822615
# ROOST_METHOD_SIG_HASH=4cff6e9ae0
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testFetchNonExistentSession',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "404 Not Found"\n' +
#       'And the details are:\n' +
#       '    "Session with ID R64EKX5RG32U not found"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test

  Background:
    * def SWAGGER_184F1D2B61_URL = karate.properties['SWAGGER_184F1D2B61_URL'] || karate.get('SWAGGER_184F1D2B61_URL', 'http://localhost:4010')
    * def SWAGGER_184F1D2B61_AUTH_TOKEN = karate.properties['SWAGGER_184F1D2B61_AUTH_TOKEN'] || karate.get('SWAGGER_184F1D2B61_AUTH_TOKEN', 'Bearer_Dummy_Token')
    * configure headers = { Authorization: '#(SWAGGER_184F1D2B61_AUTH_TOKEN)' }

  Scenario Outline: testFetchNonExistentSession
    * url SWAGGER_184F1D2B61_URL
    And path '<sessionId>'
    And headers { Authorization: '#(SWAGGER_184F1D2B61_AUTH_TOKEN)' }
    When method GET
    Then status <status>
    And match response == '{ "Session": { "ID": "<sessionId> not found" } }'

    Examples:
      | sessionId      | status |
      | 'R64EKX5RG32U' |    404 |
