# ********RoostGPT********

# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=dd2920746c
# ROOST_METHOD_SIG_HASH=f796688911
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: All API Test',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: testUpdateLocationCapacity',
#     steps: 'When the scenario executes\n' +
#       'Then the outcome should be "Success"\n' +
#       'And the details are:\n' +
#       '    "Updating capacity for location UCLocation-HBER8FXU0J to 20"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: All API Test

  Background:
    * def SWAGGER_184F1D2B61_URL = karate.properties['SWAGGER_184F1D2B61_URL'] || karate.get('SWAGGER_184F1D2B61_URL', 'http://localhost:4010')
    * def SWAGGER_184F1D2B61_AUTH_TOKEN = karate.properties['SWAGGER_184F1D2B61_AUTH_TOKEN'] || karate.get('SWAGGER_184F1D2B61_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario Outline: testUpdateLocationCapacity
    * url SWAGGER_184F1D2B61_URL
    And configure headers = { Authorization: '#(karate.properties['AUTH_TOKEN'])', accept: 'application/json', 'Content-Type': 'application/json'}
    And path '/pet/{petId}'
    And params {petId: '<petId>'}
    When request
      """
      {
        id: '<id>', 
        petId: '<petId>', 
        quantity: '<quantity>', 
        shipDate: '<shipDate>', 
        status: '<status>', 
        complete: '<complete>'
      } 
      """
    Then method post
    And status 200
    When configure headers = { Authorization: '#(karate.properties['AUTH_TOKEN'])', accept: 'application/json', 'Content-Type': 'application/json'}
    And request
      """
      {
        id: '<id>', 
        petId: '<petId>', 
        quantity: '<quantity>', 
        shipDate: '<shipDate>', 
        status: '<status>', 
        complete: '<complete>'
      } 
      """
    Then match response == {id: '#number', petId: '#number', quantity: '#number', shipDate: '#string', status: '#string', complete: '#boolean'}

    Examples:
      | id | petId | quantity | shipDate                       | status   | complete |
      | 20 |    20 |       20 | '2022-08-01T19:20:30.45+01:00' | 'placed' | false    |

  Scenario Outline: testInvalidLocationCapacity
    * url SWAGGER_184F1D2B61_URL
    And path '/pet/{petId}'
    And params {petId: '<petId>'}
    When method post
    And status 400
    Then match response contains { code: '#number', message: '#notnull', type: '#notnull', headers: 'No response headers' }

    Examples:
      | petId |
      |  9999 |
