
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=unfollowFriend_96b971ed76
ROOST_METHOD_SIG_HASH=unfollowFriend_1f03d4a510

Scenario 1: Unfollow a friend successfully with valid user names

Details:
  TestName: unfollowFriendWithValidUserNamesSuccessfully
  Description: Validate that the method correctly removes the relationship between two users when both usernames are valid and exist in the database.

Execution:
  Arrange: Prepare mock objects for ProfileDriverImpl and HttpServletRequest. Set up the mock to return a DbQueryStatus indicating success when unfollowFriend is called with the given user names.
  Act: Invoke the unfollowFriend method using valid userName and friendUserName parameters.
  Assert: Assert that the returned response contains a success status and includes the correct confirmation message in its "message" field.

Validation:
  Verify that the result correctly reflects the successful execution of the unfollow operation. Ensure that the method integrates properly with the `profileDriver.unfollowFriend` and returns correct data as per business logic.

*/

// ********RoostGPT********

package com.csc301.profilemicroservice;

import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.mockito.Mockito;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.Map;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import okhttp3.FormBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class ProfileControllerUnfollowFriendTest {

	@Test
	@Category(Categories.valid.class)
	public void unfollowFriendWithValidUserNamesSuccessfully() {
		// Arrange
		ProfileDriverImpl profileDriverMock = Mockito.mock(ProfileDriverImpl.class);
		PlaylistDriverImpl playlistDriverMock = Mockito.mock(PlaylistDriverImpl.class);
		HttpServletRequest requestMock = Mockito.mock(HttpServletRequest.class);
		Mockito.when(requestMock.getRequestURI()).thenReturn("/unfollowFriend/user1/user2");
		Mockito.when(profileDriverMock.unfollowFriend(Mockito.anyString(), Mockito.anyString()))
			.thenReturn(new DbQueryStatus("Friend successfully unfollowed", DbQueryExecResult.QUERY_OK));
		ProfileController profileController = new ProfileController(profileDriverMock, playlistDriverMock);
		// Act
		Map<String, Object> actualResponse = profileController.unfollowFriend("user1", "user2", requestMock);
		// Assert
		assertEquals("Friend successfully unfollowed", actualResponse.get("message"));
		assertEquals(DbQueryExecResult.QUERY_OK, actualResponse.get("dbQueryExecResult"));
		assertEquals("PUT /unfollowFriend/user1/user2", actualResponse.get("path"));
		assertNotNull(actualResponse.get("message"));
	}

	@Test
	@Category(Categories.invalid.class)
	public void unfollowFriendWithInvalidUserNames() {
		// Arrange
		ProfileDriverImpl profileDriverMock = Mockito.mock(ProfileDriverImpl.class);
		PlaylistDriverImpl playlistDriverMock = Mockito.mock(PlaylistDriverImpl.class);
		HttpServletRequest requestMock = Mockito.mock(HttpServletRequest.class);
		Mockito.when(requestMock.getRequestURI()).thenReturn("/unfollowFriend/invalidUser1/invalidUser2");
		Mockito.when(profileDriverMock.unfollowFriend(Mockito.anyString(), Mockito.anyString()))
			.thenReturn(new DbQueryStatus("User not found", DbQueryExecResult.QUERY_ERROR_NOT_FOUND));
		ProfileController profileController = new ProfileController(profileDriverMock, playlistDriverMock);
		// Act
		Map<String, Object> actualResponse = profileController.unfollowFriend("invalidUser1", "invalidUser2",
				requestMock);
		// Assert
		assertEquals("User not found", actualResponse.get("message"));
		assertEquals(DbQueryExecResult.QUERY_ERROR_NOT_FOUND, actualResponse.get("dbQueryExecResult"));
		assertNotNull(actualResponse.get("message"));
	}

	@Test
	@Category(Categories.boundary.class)
	public void unfollowFriendWithEdgeCaseUserNames() {
		// Arrange
		ProfileDriverImpl profileDriverMock = Mockito.mock(ProfileDriverImpl.class);
		PlaylistDriverImpl playlistDriverMock = Mockito.mock(PlaylistDriverImpl.class);
		HttpServletRequest requestMock = Mockito.mock(HttpServletRequest.class);
		Mockito.when(requestMock.getRequestURI()).thenReturn("/unfollowFriend/ / ");
		Mockito.when(profileDriverMock.unfollowFriend(Mockito.anyString(), Mockito.anyString()))
			.thenReturn(new DbQueryStatus("Invalid user names", DbQueryExecResult.QUERY_ERROR_GENERIC));
		ProfileController profileController = new ProfileController(profileDriverMock, playlistDriverMock);
		// Act
		Map<String, Object> actualResponse = profileController.unfollowFriend(" ", " ", requestMock);
		// Assert
		assertEquals("Invalid user names", actualResponse.get("message"));
		assertEquals(DbQueryExecResult.QUERY_ERROR_GENERIC, actualResponse.get("dbQueryExecResult"));
		assertNotNull(actualResponse.get("message"));
	}

	@Test
	@Category(Categories.integration.class)
	public void integrationTestUnfollowFriend() {
		// Arrange
		ProfileDriverImpl profileDriverMock = Mockito.mock(ProfileDriverImpl.class);
		PlaylistDriverImpl playlistDriverMock = Mockito.mock(PlaylistDriverImpl.class);
		HttpServletRequest requestMock = Mockito.mock(HttpServletRequest.class);
		Mockito.when(requestMock.getRequestURI()).thenReturn("/unfollowFriend/userIntegration1/userIntegration2");
		Mockito.when(profileDriverMock.unfollowFriend(Mockito.anyString(), Mockito.anyString()))
			.thenReturn(new DbQueryStatus("Integration test successful", DbQueryExecResult.QUERY_OK));
		ProfileController profileController = new ProfileController(profileDriverMock, playlistDriverMock);
		// Act
		Map<String, Object> actualResponse = profileController.unfollowFriend("userIntegration1", "userIntegration2",
				requestMock);
		// Assert
		assertEquals("Integration test successful", actualResponse.get("message"));
		assertEquals(DbQueryExecResult.QUERY_OK, actualResponse.get("dbQueryExecResult"));
		assertNotNull(actualResponse.get("message"));
	}

}