// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=579264a708
ROOST_METHOD_SIG_HASH=809947a8ba

 ########## Scenario ########## 

{
  feature: 'Feature: Petstore E2E Flow\r\n' +
    '    As a user of the Petstore API\r\n' +
    '    I want to manage pets, orders, and user accounts\r\n' +
    '    So that I can run a successful pet store business',
  background: 'Background:\r\n' +
    '        Given the Petstore API is available at "https://petstore.swagger.io/v2"\r\n' +
    '        And I have valid API credentials\r\n' +
    '        And I am authenticated with OAuth2 token with "write:pets" and "read:pets" scopes',
  rule: null,
  scenario: {
    title: 'Scenario: Bulk operations',
    steps: 'Given I have multiple users to create\r\n' +
      'When I create users with array input\r\n' +
      '            | username  | email          | firstName | lastName |\r\n' +
      '            | bulkuser1 | bulk1@test.com | Bulk      | User1    |\r\n' +
      '            | bulkuser2 | bulk2@test.com | Bulk      | User2    |\r\n' +
      'Then all users should be created successfully\r\n' +
      'Given I have multiple pets to add\r\n' +
      'When I add the following pets:\r\n' +
      '            | name    | category | status    |\r\n' +
      '            | Max     | Dog      | available |\r\n' +
      '            | Charlie | Dog      | available |\r\n' +
      'Then all pets should be added successfully',
    examples: ''
  }
}

*/

// ********RoostGPT********
package com.csc301.RoostTest;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import io.restassured.http.Method;
import io.restassured.response.Response;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.Assertions;

import static io.restassured.RestAssured.*;

public class BulkOperationsTest {

  String urlsofApisToTest = "src/test/java/com/csc301/RoostTest/BulkOperationsTest.csv";

  @BeforeEach
  public void setupPayloadData() {
    try {
      Files.lines(Paths.get(urlsofApisToTest)).skip(1).forEach(line -> {
        if (!line.isEmpty()) {
  
          String[] parts = line.split("\\^\\|\\^");
          String methodType = parts[0].trim();
          String url = parts[1].trim();
          Map<String, String> headers = parseHeaders(parts[2].trim());
          String requestBody = parts[3].trim();
          int expectedStatusCode = Integer.parseInt(parts[4].trim());
          String expectedResponseBody = parts[5].trim();

          testApi(methodType, url, headers, requestBody, expectedStatusCode, expectedResponseBody);
        }
      });
    } catch (IOException ex) {
      // handle exception here
    }
  }
  
  public Map<String, String> parseHeaders(String headerString) {
    Map<String, String> headers = new HashMap<String, String>();
    String[] pairs = headerString.split(",");
    for (int i=0; i<pairs.length; i++) {
      String pair = pairs[i];
      String[] keyValue = pair.split(":");
      headers.put(keyValue[0].trim(), keyValue[1].trim().replace("\"", ""));
    }
    return headers;
  }

  public void testApi(String methodType, String url, Map<String, String> headers, String requestBody, int expectedStatusCode, String expectedResponseBody) {
  
    Method method = Method.valueOf(methodType.toUpperCase());

    Response response = given().headers(headers).body(requestBody).request(method, url);

    Assertions.assertEquals(expectedStatusCode, response.getStatusCode());
    
    if (expectedResponseBody != null && !expectedResponseBody.isEmpty()) {
      Assertions.assertEquals(expectedResponseBody, response.getBody().asString());
    }
  }
}
