// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=f796688911
ROOST_METHOD_SIG_HASH=22e1a8dc21

 ########## Scenario ########## 

{
  feature: 'Feature: All API Test',
  background: null,
  rule: null,
  scenario: {
    title: 'Scenario: testUpdateLocationCapacity',
    steps: 'When the scenario executes\n' +
      'Then the outcome should be "Success"\n' +
      'And the details are:\n' +
      '    "Updating capacity for location UCLocation-HBER8FXU0J to 20"',
    examples: ''
  }
}

*/

// ********RoostGPT********
package com.csc301.RoostTest;

import io.restassured.response.Response;
import io.restassured.RestAssured;
import org.apache.http.HttpStatus;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;


public class TestUpdateLocationCapacityTest {

    private static final Path PAYLOAD_FILE_PATH = FileSystems.getDefault().getPath("src", "test", "java", "com", "csc301", "RoostTest", "TestUpdateLocationCapacityTest.csv");
    private BufferedReader reader;

    @BeforeEach
    public void setup() throws IOException {
        reader = new BufferedReader(new FileReader(PAYLOAD_FILE_PATH.toFile()));
        // Skipping the header
        reader.readLine();
    }

    @Test
    public void testUpdateLocationCapacity() throws Exception {
        String line;
        while ((line = reader.readLine()) != null) {
            if (line.trim().isEmpty()) { continue; }
            String[] payloadData = line.split("\\^\\|\\^");
            String method = payloadData[0];
            String url = payloadData[1];
            JSONParser jsonParser = new JSONParser();
            JSONObject headersObject = (JSONObject) jsonParser.parse(payloadData[2]);
            JSONObject bodyObject = (JSONObject) jsonParser.parse(payloadData[3]);
            int responseCode = Integer.parseInt(payloadData[4]);
            JSONObject responseBodyObject = (JSONObject) jsonParser.parse(payloadData[5]);
            Map<String, String> headers = new HashMap<>();
            for (Object key : headersObject.keySet()) {
                headers.put((String) key, (String) headersObject.get(key));
            }
            Response response;
            switch (method.toUpperCase()) {
                case "POST":
                    response = RestAssured.given().headers(headers).body(bodyObject.toJSONString()).when().post(url);
                    break;
                case "GET":
                    response = RestAssured.given().headers(headers).when().get(url);
                    break;
                case "PUT":
                    response = RestAssured.given().headers(headers).body(bodyObject.toJSONString()).when().put(url);
                    break;
                case "DELETE":
                    response = RestAssured.given().headers(headers).when().delete(url);
                    break;
                default:
                    throw new IllegalStateException("Unexpected value: " + method);
            }
            assertThat(response.getStatusCode()).isEqualTo(responseCode);
            assertThat(response.getBody().asString()).isEqualTo(responseBodyObject.toJSONString());
        }
    }
}
