// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=4cff6e9ae0
ROOST_METHOD_SIG_HASH=b2948c3472

 ########## Scenario ########## 

{
  feature: 'Feature: All API Test',
  background: null,
  rule: null,
  scenario: {
    title: 'Scenario: testFetchNonExistentSession',
    steps: 'When the scenario executes\n' +
      'Then the outcome should be "404 Not Found"\n' +
      'And the details are:\n' +
      '    "Session with ID R64EKX5RG32U not found"',
    examples: ''
  }
}

*/

// ********RoostGPT********
package com.csc301.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.response.Response;
import io.restassured.response.ValidatableResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.is;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Map;

public class TestFetchNonExistentSessionTest {

    @BeforeEach
    public void setup() throws IOException {
        RestAssured.baseURI = "http://localhost";
        RestAssured.port = 8080;
    }

    @Test
    public void testFetchNonExistentSession() throws IOException {

        BufferedReader br = new BufferedReader(new FileReader("src/test/java/com/csc301/RoostTest/TestFetchNonExistentSessionTest.csv"));
        String line = br.readLine();

        while ((line = br.readLine()) != null && !line.isEmpty()) {
            String[] data = line.split("\\^\\|\\^");

            String method = data[0];
            String url = data[1];
            Map<String, String> headers = JsonPath.from(data[2]).get();
            String body = data[3];
            int statusCode = Integer.parseInt(data[4]);
            String responseBody = data[5];

            switch (method.toUpperCase()) {
                case "GET":
                    getAPI(url, headers, statusCode, responseBody);
                    break;
                case "POST":
                    postAPI(url, headers, body, statusCode, responseBody);
                    break;
                case "PUT":
                    putAPI(url, headers, body, statusCode, responseBody);
                    break;
                case "DELETE":
                    deleteAPI(url, headers, statusCode, responseBody);
                    break;
            }
        }
        br.close();
    }

    private void getAPI(String url, Map<String, String> headers, int statusCode, String responseBody) {
        given()
            .headers(headers)
            .when()
            .get(url)
            .then()
            .statusCode(statusCode)
            .body(is(responseBody));
    }

    private void postAPI(String url, Map<String, String> headers, String body, int statusCode, String responseBody) {
        given()
            .headers(headers)
            .body(body)
            .when()
            .post(url)
            .then()
            .statusCode(statusCode)
            .body(is(responseBody));
    }

    private void putAPI(String url, Map<String, String> headers, String body, int statusCode, String responseBody) {
        given()
            .headers(headers)
            .body(body)
            .when()
            .put(url)
            .then()
            .statusCode(statusCode)
            .body(is(responseBody));
    }

    private void deleteAPI(String url, Map<String, String> headers, int statusCode, String responseBody) {
        given()
            .headers(headers)
            .when()
            .delete(url)
            .then()
            .statusCode(statusCode)
            .body(is(responseBody));
    }
}
